[package]
name = "pcd-rs-derive"
version = "0.5.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
description = "Derive macros for pcd-rs crate"
documentation = "https://docs.rs/pcd-rs-derive/"
repository = "https://github.com/jerry73204/pcd-rs"
homepage = "https://github.com/jerry73204/pcd-rs"
license-file = "LICENSE"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.0"
syn = { version = "1.0.0", features = ["extra-traits"] }
quote = "1.0.0"
regex = "1.3.0"
